#:kivy 1.0

<GoStone>
    image: piece_image
    label: annotation

    Image:
        id: piece_image
        mipmap: True
        center: root.center
        width:  root.width
        height: root.height
        source: root.color + '.png'

    Label:
        id: annotation
        center: root.center
        font_size: root.height / 4
        text: root.annotation
        color: [0,0,0,1] if root.color == 'white' else [1,1,1,1]
